### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by tunderhill** [RittmanMead/VPP#1]
What files on obiee 12c need to be modified. I found a lot of common.js files, but not sure which ones need to be updated. I found two similar files from your instructions under

user_projects/domains/bi/servers/bi_server1/tmp/_WL_user/analytics

./eiguw6/war/res/b_mozilla/common.js
./za01ic/war/res/b_mozilla/common.js

I added the new var src to both, but didn't seem to work.

**Comment by tunderhill** [comment]
Out of date installation instructions in the Wiki, replaced with https://github.com/RittmanMead/VPP/tree/master/rmvpp/docs/install.md

**Comment by zakaryanla** [comment]
Installed strictly on the tool, the button did not appear. What could be the reason?
OBI 12.2.1.3.0
